### Numpy

→ Numerical Python

→ 산술계산을 위한 패키지

→ Numpy의 배열 객체를 데이터 교환을 위한 공통 언어처럼 사용

→ ndarray라고 하는 N차원의 배열 객체 (대규모 데이터 집합을 담을 수 있는 자료구조)

In [1]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


In [ ]:
# 뒤에 .을 넣을 경우 다 float으로 변환
b = np.array([1,2,3.])
print(b, type(b))

[1. 2. 3.] <class 'numpy.ndarray'>


In [ ]:
# 리스트 vs Numpy

l = [1,2,3]
a = np.array([1,2,3])
print(l)
print(a) # numpy: print로 출력시 컴마x
a

[1, 2, 3]
[1 2 3]


array([1, 2, 3])

In [ ]:
for item in l:
  print(item)

1
2
3


In [ ]:
for item in a:
  print(item)

1
2
3


In [ ]:
l.append(4)
print(l)

[1, 2, 3, 4]


In [ ]:
# numpy append 지원 x
a.append(4)
print(a)

AttributeError: ignored

In [ ]:
a = np.append(a, 4)
print(a)

[1 2 3 4]


In [ ]:
print(l)
l = l + [5]
print(l)

[1, 2, 3, 4]
[1, 2, 3, 4, 5]


In [ ]:
# 브로드케스팅
print(a)
a = a + np.array([5])
print(a)

[1 2 3 4]
[6 7 8 9]


In [ ]:
# list *2
l = [1,2,3]
l2 = []
for item in l: 
  l2.append(item*2)
print(l2)

[2, 4, 6]


In [ ]:
# ndarray *2
l = [1,2,3]
a = np.array(l)
a2 = a*2
print(a2)

[2 4 6]


In [ ]:
l = [1,2,3]
print(l)
l = l * 2
print(l)

[1, 2, 3]
[1, 2, 3, 1, 2, 3]


# numpy 배열

→ 모두 같은 유형의 값

→ 정수의 튜플로 인덱싱

→ 차원의 수는 배열의 랭크

→ 배열의 shape은 각 차원별 배열 크기의 튜플

→ 중첩된 파이썬 리스트로부터 배열 초기화

→ 대괄호 사용하여 요소에 접근 가능

In [ ]:
a = np.array([1,2,3])
print(a)
print(type(a), a.ndim, a.shape, a.dtype)

[1 2 3]
<class 'numpy.ndarray'> 1 (3,) int64


asarray vs array

In [ ]:
# 같은 어레이
b = np.asarray(a)
print(b)

[1 2 3]


In [ ]:
b[0] = 9
print(a)
print(b)

[9 2 3]
[9 2 3]


In [ ]:
# 새로운 카피
a = np.array([1,2,3])
b = np.array(a)
print(b)

[1 2 3]


In [ ]:
b[0] = 9
print(a)
print(b)

[1 2 3]
[9 2 3]


### 배열 생성

In [ ]:
a = np.zeros((3,4))
print(a)
print(a.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [ ]:
b = np.ones((5,2))
print(b)
print(b.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
float64


In [ ]:
c = np.full((2,3),4)
print(c)

[[4 4 4]
 [4 4 4]]


In [ ]:
d = np.empty((3,3))
print(d)

[[2.17361849e-316 1.77863633e-322 0.00000000e+000]
 [0.00000000e+000 4.34900600e+199 5.04247196e+174]
 [4.99029685e+174 6.81735047e-091 2.00424248e-052]]


In [6]:
a = np.array([1,2,3])
a = np.zeros((3,4))
e = np.zeros_like(a)
f = np.ones_like(a)
g = np.full_like(a, 2)
h = np.empty_like(a)
print(a)
print("-------")
print(e)
print(f)
print(g)
print(h)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[1.02420994e-316 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [10]:
i = np.eye(3)
j = np.identity(3)
print(i)
print(j)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
k = np.arange(10)
print(k)
k = np.arange(1, 10)
print(k)
k = np.arange(10, 0, -1)
print(k)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[10  9  8  7  6  5  4  3  2  1]


In [15]:
# uniform distribution
l = np.random.rand(2, 2)
print(l)

[[0.9334884  0.99984344]
 [0.5423903  0.81517839]]


In [20]:
# normal distribution
m = np.random.randn(2,2)
print(m)

[[1.17897345 0.18292245]
 [0.07843505 1.41429469]]
