### Numpy

→ Numerical Python

→ 산술계산을 위한 패키지

→ Numpy의 배열 객체를 데이터 교환을 위한 공통 언어처럼 사용

→ ndarray라고 하는 N차원의 배열 객체 (대규모 데이터 집합을 담을 수 있는 자료구조)

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


In [4]:
# 뒤에 .을 넣을 경우 다 float으로 변환
b = np.array([1,2,3.])
print(b, type(b))

[1. 2. 3.] <class 'numpy.ndarray'>


In [33]:
# 리스트 vs Numpy

l = [1,2,3]
a = np.array([1,2,3])
print(l)
print(a) # numpy: print로 출력시 컴마x
a

[1, 2, 3]
[1 2 3]


array([1, 2, 3])

In [7]:
for item in l:
  print(item)

1
2
3


In [8]:
for item in a:
  print(item)

1
2
3


In [28]:
l.append(4)
print(l)

[1, 2, 3, 4]


In [12]:
# numpy append 지원 x
a.append(4)
print(a)

AttributeError: ignored

In [34]:
a = np.append(a, 4)
print(a)

[1 2 3 4]


In [30]:
print(l)
l = l + [5]
print(l)

[1, 2, 3, 4]
[1, 2, 3, 4, 5]


In [35]:
# 브로드케스팅
print(a)
a = a + np.array([5])
print(a)

[1 2 3 4]
[6 7 8 9]


In [38]:
# list *2
l = [1,2,3]
l2 = []
for item in l: 
  l2.append(item*2)
print(l2)

[2, 4, 6]


In [39]:
# ndarray *2
l = [1,2,3]
a = np.array(l)
a2 = a*2
print(a2)

[2 4 6]


In [40]:
l = [1,2,3]
print(l)
l = l * 2
print(l)

[1, 2, 3]
[1, 2, 3, 1, 2, 3]
